server.port=8080
spring.application.name=gestion-membres

spring.datasource.url=${URL}
spring.datasource.username=${USERNAME}
spring.datasource.password=${PASSWORD}
#Configuration JPA/Hibernate
#update → met à jour les tables sans perdre les données
spring.jpa.hibernate.ddl-auto=update
#Affiche les requêtes SQL dans la console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

server.servlet.jsp.init-parameters.development=true

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

logging.file.name=logs/gym-management.log

spring.web.resources.static-locations=classpath:/static/

